sonar.projectKey=iurilimamarques_prova01-unit-iurilimamarques
sonar.organization=iurilimamarques
sonar.projectName=prova01-unit-iurilimamarques
sonar.projectVersion=1.0
sonar.sources=./src
sonar.tests=./test
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=./coverage/lcov.info